name: Minecraft Build

# Trigger: bei Push oder Pull Request auf main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Java JDK 17 installieren
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Gradlew ausführbar machen (Linux braucht das)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Gradle Build ausführen im No-Daemon-Modus und mit genügend Speicher
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -Dorg.gradle.jvmargs="-Xmx1024m"

      # Die gebaute JAR als Artefakt hochladen (Version v4)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-mod
          path: build/libs/*.jar
